#!/usr/bin/env python3
"""Bundle a Lambda Feedback package evaluator for the Python Reactor guest."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys
from typing import Iterable


DEFAULT_EXCLUDES = {"__pycache__"}


def module_name_from_file(root: Path, path: Path) -> str:
    rel = path.relative_to(root)
    parts = list(rel.with_suffix("").parts)
    if parts[-1] == "__init__":
        parts = parts[:-1]
    return ".".join(parts)


def iter_python_files(root: Path) -> Iterable[Path]:
    for path in sorted(root.rglob("*.py")):
        if set(path.relative_to(root).parts) & DEFAULT_EXCLUDES:
            continue
        yield path


def collect_fixture_modules(root: Path) -> tuple[dict[str, str], set[str]]:
    modules: dict[str, str] = {}
    packages: set[str] = set()
    for path in iter_python_files(root):
        if path.name.endswith("_test.py") or path.name.endswith("_tests.py") or path.name == "dev.py":
            continue
        name = module_name_from_file(root, path)
        if not name:
            continue
        modules[name] = path.read_text()
        if path.name == "__init__.py":
            packages.add(name)
    return modules, packages


def collect_adapter_modules(adapter_root: Path) -> tuple[dict[str, str], set[str]]:
    adapter_file = adapter_root / "lf_compat_adapter.py"
    if not adapter_file.exists():
        raise FileNotFoundError(f"adapter module not found: {adapter_file}")

    modules = {"lf_compat_adapter": adapter_file.read_text()}
    packages: set[str] = set()
    toolkit_root = adapter_root / "lf_toolkit"
    if not toolkit_root.exists():
        return modules, packages

    for path in iter_python_files(toolkit_root):
        name = module_name_from_file(adapter_root, path)
        if not name:
            continue
        modules[name] = path.read_text()
        if path.name == "__init__.py":
            packages.add(name)
    return modules, packages


def module_part(entrypoint: str) -> str:
    if ":" not in entrypoint:
        raise ValueError(f"entrypoint must use module:function form: {entrypoint!r}")
    module, symbol = entrypoint.rsplit(":", 1)
    if not module or not symbol:
        raise ValueError(f"entrypoint must use module:function form: {entrypoint!r}")
    return module


def render_bundle(
    modules: dict[str, str],
    packages: set[str],
    eval_entrypoint: str,
    preview_entrypoint: str | None,
) -> str:
    modules_literal = repr(modules)
    packages_literal = repr(packages)
    preview_literal = repr(preview_entrypoint or "")

    preview_definition = ""
    if preview_entrypoint:
        preview_definition = '''\n\ndef preview_function(response, answer=None, params=None):\n    # The Reactor guest calls preview(response, params); the optional answer\n    # form keeps the generated adapter convenient to exercise locally.\n    if params is None and isinstance(answer, dict):\n        params, answer = answer, None\n    fn = _lf_load_entrypoint(_LF_PREVIEW_ENTRYPOINT)\n    return _lf_normalize_result(_lf_call_function(fn, "preview", response, answer, params or {}))\n'''

    return f'''# Generated by tools/lf-bundle-python/lf_bundle_python.py.\nfrom __future__ import annotations\n\nimport importlib.abc as _lf_abc\nimport importlib.machinery as _lf_machinery\nimport sys as _lf_sys\n\n_LF_BUNDLE_MODULES = {modules_literal}\n_LF_BUNDLE_PACKAGES = {packages_literal}\n\n\nclass _LambdaFeedbackBundleLoader(_lf_abc.MetaPathFinder, _lf_abc.Loader):\n    def find_spec(self, fullname, path=None, target=None):\n        if fullname not in _LF_BUNDLE_MODULES:\n            return None\n        spec = _lf_machinery.ModuleSpec(\n            fullname,\n            self,\n            is_package=fullname in _LF_BUNDLE_PACKAGES,\n        )\n        if fullname in _LF_BUNDLE_PACKAGES:\n            spec.submodule_search_locations = []\n        return spec\n\n    def create_module(self, spec):\n        return None\n\n    def exec_module(self, module):\n        name = module.__spec__.name\n        if name in _LF_BUNDLE_PACKAGES:\n            module.__path__ = []\n        source = _LF_BUNDLE_MODULES[name]\n        exec(compile(source, "<lf-bundle:" + name + ">", "exec"), module.__dict__)\n\n\n_lf_loader = _LambdaFeedbackBundleLoader()\nif not any(isinstance(loader, _LambdaFeedbackBundleLoader) for loader in _lf_sys.meta_path):\n    _lf_sys.meta_path.insert(0, _lf_loader)\n\nfrom lf_compat_adapter import call_function as _lf_call_function\nfrom lf_compat_adapter import load_entrypoint as _lf_load_entrypoint\nfrom lf_compat_adapter import normalize_result as _lf_normalize_result\n\n_LF_EVAL_ENTRYPOINT = {eval_entrypoint!r}\n_LF_PREVIEW_ENTRYPOINT = {preview_literal}\n\n\ndef evaluation_function(response, answer, params=None):\n    fn = _lf_load_entrypoint(_LF_EVAL_ENTRYPOINT)\n    return _lf_normalize_result(_lf_call_function(fn, "eval", response, answer, params or {{}}))\n{preview_definition}'''


def build_bundle(
    root: Path,
    adapter_root: Path,
    eval_entrypoint: str,
    preview_entrypoint: str | None,
) -> str:
    root = root.resolve()
    adapter_root = adapter_root.resolve()
    modules, packages = collect_fixture_modules(root)
    adapter_modules, adapter_packages = collect_adapter_modules(adapter_root)
    modules.update(adapter_modules)
    packages.update(adapter_packages)

    for entrypoint in (eval_entrypoint, preview_entrypoint):
        if not entrypoint:
            continue
        module = module_part(entrypoint)
        if module not in modules:
            raise ValueError(f"entrypoint module {module!r} was not collected")

    return render_bundle(modules, packages, eval_entrypoint, preview_entrypoint)


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", required=True, type=Path)
    parser.add_argument("--adapter-root", required=True, type=Path)
    parser.add_argument("--eval-entrypoint", required=True)
    parser.add_argument("--preview-entrypoint", default="")
    parser.add_argument("--out", required=True, type=Path)
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(sys.argv[1:] if argv is None else argv)
    try:
        bundle = build_bundle(
            root=args.root,
            adapter_root=args.adapter_root,
            eval_entrypoint=args.eval_entrypoint,
            preview_entrypoint=args.preview_entrypoint or None,
        )
    except Exception as exc:
        print(f"lf-bundle-python: {exc}", file=sys.stderr)
        return 1

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(bundle)
    print(args.out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
